// 1

/*
var tips = [
  "JavaScript is a dynamic computer programming language.",
  "It is lightweight.",
  "most commonly used as a part of web pages.",
  "allow client-side script to interact with the user",
  "It is an interpreted programming language with object-oriented capabilities",
  "JavaScript was first known as LiveScript",
  "Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java",
  "JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript",
  "Designed for creating network-centric applications.",
  "Open and cross-platform",
  "Complementary to and integrated with HTML.",
];

var random = Math.floor(Math.random() * tips.length);
document.write("<h1>JS Tip Of The Day: " + tips[random] + "</h1>");
*/

// 2
/*
var arr = [];
for (var i = 0; i < 3; i++) {
  do {
    var inputNum = prompt("Enter a number please: (only numbers accepted!)");
  } while (isNaN(inputNum));
  arr.push(inputNum);
}
var sum = 0;
var mult = 1;
var div = 1;

arr.forEach(function (element) {
  sum += parseInt(element);
  mult *= element;
  div /= element;
});

document.write(
  "<p style='color:green'>Sum of the three values: </p>" +
    arr.join("+") +
    " = " +
    sum
);
document.write(
  "<p style='color:green'>Multiplication of the three values: </p>" +
    arr.join("*") +
    " = " +
    mult
);
document.write(
  "<p style='color:green'>Division of the three values: </p>" +
    arr.join("/") +
    " = " +
    div
);
*/

// 3
function values() {
  var reversed = [];
  for (var i = arguments.length - 1; i >= 0; i--) {
    reversed.push(arguments[i]);
  }
  return reversed;
}

console.log(values(1, 2, 3));
